### ISSUE TITLE
"Credit"

### ISSUE THREAD

**Issue by bhopalex** [Nolan-O/bTimes#11]
Take my name off of this. Obviously it is too late to remove, as many have already seen it, but I don't condone you putting this on github and don't appreciate you crediting me for some reason.

**Comment by Nolan-O** [comment]
You're right and I apologize. It was an inappropriate joke and I wasn't thinking of how likely it was that people might think it was genuinely crediting you.

For what it is worth, in the times that people did ask me if that was serious, I would make it clear that you were not actually involved. I know that doesn't actually change much nor does it excuse anything. I guess I just want to say that I wasn't actually trying to push a narrative of you being involved.
