### ISSUE TITLE
can you attact tas for timer? i give sourcecode for u

### ISSUE THREAD

**Issue by hitlerjugend** [Nolan-O/bTimes#17]
[bTimes-tas.zip](https://github.com/Nolan-O/bTimes/files/1539624/bTimes-tas.zip)

**Comment by Nolan-O** [comment]
lmao where did you get that

**Comment by Nolan-O** [comment]
Anyway, I won't be including this because it is probably incompatible with the bTimes includes, and also part of a version of the timer that would probably actually upset someone if it started getting leaked.

**Comment by AcerGit** [comment]
Hitlerjugend. if you have .sp/.smx for whole 2.0 timer, can you post them? there are more than one files that need to be changed for 1.8.3 and some are missing:
#include <bTimes-climbcp>
#include <bTimes-saveloc>

this will make it much easier to make it work for 1.8.3
