### ISSUE TITLE
replay bots commit suicide and end zone is not working

### ISSUE THREAD

**Issue by pdy-x** [Nolan-O/bTimes#19]
#hi
the bots always commit suicide ... the round is ended, starts again and the bots commit suicide again
and on some maps there are no bots (for example, arcane)
and the main end zone is not working properly the time is not stopped
can someone help me?

**Comment by Atrykx** [comment]
> L 03/11/2018 - 19:15:06: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 03/11/2018 - 19:15:06: [SM] Blaming: bTimes-zones.smx
L 03/11/2018 - 19:15:06: [SM] Call stack trace:
L 03/11/2018 - 19:15:06: [SM]   [0] FindStringInArray
L 03/11/2018 - 19:15:06: [SM]   [1] Line 1315, D:\testserver\cstrike\addons\sourcemod\scripting\bTimes-zones.sp::LoadZones_Callback2

**Comment by Nolan-O** [comment]
Looks like you don't have a map list.

**Comment by Atrykx** [comment]
ah that with the records works now, thank you :)
but why do the bots die if there is no wr? the console says "committed suicide with"world""
and why is the name of the bot not changed to wr holder? the clantag is not as it stands in the ghost.cfg
sorry for all the questions and my bad english (google translate) :/ :D
