### ISSUE TITLE
Error spamming in bTimes-ghost not actually fixed.

### ISSUE THREAD

**Issue by Nolan-O** [Nolan-O/bTimes#4]
I cannot track down what circumstances cause it due to its infrequent and sudden nature of occurrence; anyone using this version of the timer please provide any information you might have.

**Comment by Skyline23** [comment]
"Error spamming" is mean after load bTimes-ghost?

**Comment by Nolan-O** [comment]
Well the plugin has to be loaded for it to work, and it doesn't unload from the error, but I can't tell what happens that is causing it.

**Comment by Skyline23** [comment]
not so understand.cant unload it?

**Comment by Nolan-O** [comment]
I'm actually thinking that it is fixed because I've had this up on a public server for 4 days with no error spam. I might have been looking at logs that were pending at the time I changed out the plugin.
