### ISSUE TITLE
[ghost] some stuff

### ISSUE THREAD

**Issue by shavitush** [Nolan-O/bTimes#6]
> GetClientEyeAngles(client, vAng);

you could use angles[3] from OnPlayerRunCmd

> ScaleVector(vVel, 100.0);

this will only work properly on 100tick; you can fix like that:

```
float gF_Tickrate = 0.0;

public void OnPluginStart()
{
	gF_Tickrate = (1.0 / GetTickInterval());
}

ScaleVector(vVel, gF_Tickrate);
```
cant really send a pull request, git is doing unexpected stuff for me :x

**Comment by Nolan-O** [comment]
I'm not sure what's causing this and I'm too busy to figure it out for the mom
